<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="asset/css/bootstrap.min.css">
    <link rel="stylesheet" href="asset/css/bootstrap-grid.min.css">
</head>

<body>
    <header>
        <nav class="navbar navbar-light bg-light">
            <ul>
                <?php if(isset($_SESSION['links'])): ?>
                    <?php foreach($_SESSION['links'] as $link): ?>
                    <li><a href="index.php?goto=<?=$link['navGoto']?>&target=<?=$link['navTarget']?>"><?=$link['LinksName']?></a></li>
                    <?php endforeach ?>
                 <?php endif ?>   
            </ul>

        </nav>
    </header>
    <main class="container">
    <?php include $template ?>
    </main>
    <script src="asset/js/bootstrap.min.js"></script>
</body>

</html>