    <form action="" method="post">
        <fieldset>
            <legend>
                CONNEXION
            </legend>
            <label for="id_user">Identifiant</label>
            <input type="text" name="id_user" id="id_user"><br/> 
            <label for="pwd">Mot de pass</label>
            <input type="password" name="pwd" id="pwd"><br/> 
            <button type="submit" name="connexion">Connexion</button>
            <p>Vous n'avez pas encore de compte. Veuillez vous <a href="index.php?goto=user&target=store">Inscrire</a></p>
        </fieldset>

    </form>