<div>
    <form action="" method="post">
    <label for="id_user"> Identifiant : </label>
            <input type="hidden" name="user" value="<?=(isset($admin['Id'])) ?>">
            <input type="text" name="id_user" id="id_user" value="<?=(isset($admin['AdLogin']))?$admin['AdLogin']:""?>"><br>
            <label for="pwd"> Mot de pass : </label>
            <input type="password" name="pwd" id="pwd"><br>
            <label for="pwd"> Confirmer le mot de pass : </label>
            <input type="password" name="cpwd" id="cpwd"><br>
            <input type="submit" name="inscription" id="inscription" value="Valider">
    </form>
</div>